# Numpy Library


In [1]:
import numpy as np 
np.__version__

'1.21.5'

# CREATE AN ARRAY USING ARRAY FUNCTION 

# CREATE A ONE DIMENTIONAL ARRAY USIND  ARANGE FUNTION 

In [2]:
import numpy as np
a=np.arange(1,5)
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4]
int32
(4,)


# CREATE 2 DIMENTION USING ARRAY FUNCTION

In [12]:
import numpy as np
a=np.array([
    [1,2,3,4,],[5,6,7,8]
])
print(a)
print(a.dtype)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
int32
(2, 4)


# CREATE A 2 DIMENTIONAL ARRAY USING ARANGE FUNTION

In [5]:
import numpy as np
a=np.arange(12).reshape(2,6)#MULTIPLY MUST RESULT SAME RANGE
print(a)
print(a.dtype)
print(a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
int32
(2, 6)


# CREATE A 3 DIMENTION ARRAY USING ARRAY FUNTION 

In [21]:
import numpy as np 
a=np.array(
    [
     [[1,2],[3,4]],
      [[5,6],[7,8]],
       [[9,10],[11,12]]
]
)
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# CREAT A 3 DIMENTIONAL ARRAY USING ARANGE FUNTION 

In [22]:
import numpy as np
a=np.arange(1,19).reshape(3,3,2) 
print(a)
print()
print(a.dtype)
print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]

int32
(3, 3, 2)


# CREATING ARRAY OF ONCS

In [7]:
import numpy as np 
a=np.ones(10,dtype='int32')
print(a)
print(a.dtype)
print(a.shape)

[1 1 1 1 1 1 1 1 1 1]
int32
(10,)


# CREATING ARRAY OF ONES (2 DIMENTION)


In [8]:
import numpy as np
a=np.ones((6,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int32
(6, 3)


# CREATING ARRAY OF ONES 3 DIMENSION

In [9]:
import numpy as np
a=np.ones((3,2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# CREATING ARRAY OF ZEROS (1-D)

In [33]:
import numpy as np
a=np.zeros(3,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[0 0 0]
int32
(3,)


# CREATING ARRAY OF ZEROS (2-D)

In [10]:
import numpy as np
a=np.zeros((3,3),dtype='int32')
print(a)
print(a.dtype)
print(a.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32
(3, 3)


# CREATING ARRAY OF ZEROS (3-D)


In [14]:
import numpy as np
a=np.zeros((1,3,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]]
int32
(1, 3, 3)


# CREATING AN ARRAY WITH RANDOM NUMBERS (1-D)

In [16]:
import numpy as np
a=np.random.randint(1,11,size=(3)) #size=reshape
print(a)
print(a.dtype)
print(a.shape)

[7 3 3]
int32
(3,)


# CREATING AN ARRAY WITH RANDOM NUMBERS (2-D)

In [46]:
import numpy as np
a=np.random.randint(1,11,size=(4,5))
print(a)
print(a.dtype)
print(a.shape)

[[6 3 8 5 4]
 [8 2 5 7 4]
 [3 6 3 5 5]
 [5 9 8 7 7]]
int32
(4, 5)


# CREATING AN ARRAY WITH RANDOM NUMBERS (3-D)

In [49]:
import numpy as np
a=np.random.randint(1,11,size=(1,5,3))
print(a)
print(a.dtype)
print(a.shape)

[[[ 3  3  7]
  [ 9  4  1]
  [ 9  4  4]
  [ 9  2  2]
  [10  8  6]]]
int32
(1, 5, 3)


# CREATING AN ARRAY SINGLE LOW MULTIPLE HIGH

In [18]:
import numpy as np
a = np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 5 17 15]
int32
(3,)


# CREATING ARRRAY EQUAL LOW AND HIGH

In [67]:
import numpy as np
a=np.random.randint([2,4,6],[6,8,10],size=(3,2,3))#no of element == no of colums 
print(a)
print(a.dtype)
print(a.shape)

[[[4 5 8]
  [4 7 6]]

 [[5 4 6]
  [3 4 9]]

 [[3 6 6]
  [2 4 7]]]
int32
(3, 2, 3)


# CREATING AN ARRAY WITH MULTIPLE LOW WITH ONE HIGH

In [21]:
import numpy as np
a=np.random.randint([1,2,3],4)
print(a)
print(a.dtype)
print(a.shape)

[3 3 3]
int32
(3,)


# CREATING A ARRAY USING RANDOM()

In [23]:
import numpy as np
a=np.random.randn(3)
print(a)
print(a.dtype)
print(a.shape)

[ 0.41408388 -0.97386959 -1.05557458]
float64
(3,)


In [27]:
import numpy as np
a=np.random.randn(3,3)
print(a)
print(a.dtype)
print(a.shape)

[[-1.37385085e+00  5.44857541e-01 -2.86803057e-01]
 [ 1.85036783e+00  8.58261491e-01  1.19775241e-03]
 [-6.88405046e-01  1.87612116e+00 -4.13264025e-01]]
float64
(3, 3)


# CREATING AN ARRAY USING RAND()

In [30]:
import numpy as np
a=np.random.rand(3)
print(a)
print(a.dtype)
print(a.shape)

[0.94907377 0.97298239 0.62493843]
float64
(3,)


In [31]:
import numpy as np
a=np.random.rand(3,3)
print(a)
print(a.dtype)
print(a.shape)

[[0.01532418 0.91092239 0.22434252]
 [0.61366661 0.69463749 0.26917108]
 [0.89064006 0.45670891 0.29060844]]
float64
(3, 3)


In [32]:
import numpy as np
a=np.random.rand(3,3,2)
print(a)
print(a.dtype)
print(a.shape)

[[[0.63135787 0.18637186]
  [0.40742581 0.72084617]
  [0.09924947 0.02513917]]

 [[0.81187586 0.0715163 ]
  [0.9374703  0.87126375]
  [0.20819093 0.55580269]]

 [[0.93340824 0.97000333]
  [0.04059398 0.26247516]
  [0.38513586 0.92894269]]]
float64
(3, 3, 2)


# POSITIVE INDEXING IN ARRAY 

In [ ]:
#ARRAY IN 1-D

In [34]:
import numpy as np
arr=np.array([9,8,7,6])
print(arr[1])

8


In [ ]:
#ARRAY IN 2-D

In [36]:
import numpy as np
arr=np.array([[9,8,7,6],[5,4,3,2]])
print(arr[1,0])
print(arr[0,3])

5
6


In [ ]:
#ARRAY IN 3-D

In [43]:
import numpy as np
arr=np.array([[[1,1,1],[1,1,1]],[[2,2,2],[2,6,2]],[[3,3,3],[3,9,3]]])
print(arr[1,1,1])
print(arr[2,1,1])

6
9


# NEGATIVE INDEXING IN ARRAY 

In [ ]:
#ARRAY IN 1-D

In [44]:
import numpy as np
arr=np.array([4,5,1,0])
print(arr[-3])

5


In [ ]:
#ARRAY IN 2-D

In [45]:
import numpy as np
arr=np.array([[4,5,7],[1,0,6]])
print(arr[-2,-2])

5


In [ ]:
#ARRAY IN 3-D

In [50]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]],[[9,4,0],[3,-2,2]]])
print(arr[-1,-2,-1])
print(arr[-1,-1,2])

0
2


# MIX + -

In [ ]:
#ARRAY IN 3-D

In [59]:
import numpy as np
arr=np.array([[[9,4,0],[3,2,2]],[[9,8,5],[7,7,7]],[[4,8,7],[1,1,9]]])
print(arr[-3,-1,-2])
print(arr[1,-1,1])
print(arr[0,0,1])
print(arr[-3,-2,-1])

2
7
4
0


# NUMPY ARRAY SLICING

In [ ]:
#SLICE ELEMENT FROM INDEX 1 TO INDEX 5 FROM THE FOLLOWING ARRAY 

In [60]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[1:5])

[2 3 4 5]


In [ ]:
#SLICE ELEMENT FROM INDEX 4 TO THE END OF THE ARRAY

In [61]:
import numpy as np
a=np.array([9,4,0,3,2,])
print(a[4:])

[2]


In [ ]:
#SLICE ELEMENT FROM THE BEGINNING TO INDEX 4 (NOT INCLUDED)

In [62]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[:4])

[1 2 3 4]


# NEGATIVE SLICING

In [ ]:
# SLICE FROM THE INDEX 3 FROM THE END TO INDEX 1 FROM THE END

In [63]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[-3:-1])

[5 6]


In [ ]:
# RETURN EVERY OTHER ELEMENT FROM INDEX 1 TO INDEX 5

In [67]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,])
print(a[1:5:2])

[2 4]


In [ ]:
# RETURN EVERY OTHER ELEMENT FROM THE ENTIRE ARRAY

In [68]:
import numpy as np
a=np.array([9,8,7,6,5,4,3])
print(a[::2])

[9 7 5 3]


# SLICING 2-D ARRAY

In [ ]:
# FROM THE SECOND ELEMENT,SLICE ELEMENTS FROM INDEX 1 TO INDEX 4 (NOT INCLUDED)

In [78]:
import numpy as np
a=np.array([[9,8,7,6],[5,4,3,2]])
print(a[1,1:4])

[4 3 2]


In [79]:
# FROM THE BOTH ARRAYS,RETURNS INDEX 2 

In [80]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,2])

[3 8]


In [ ]:
# FROM BOTH ELEMENTS SLICE INDEX 1 TO INDEX 4 (NOT INCLUDED) THIS WILL RETURN A 2-D ARRAY 

In [84]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NUMPY ARRAY COPY VS VIEW

# COPY

In [8]:
import numpy as np
a=np.array([1,2,3,4,6])
b=np.copy(a)
print(a)
b[0]=45
print(b)


[1 2 3 4 6]
[45  2  3  4  6]


# VIEW

In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.view()
a[2]=5
print(a)
print(b)

[1 2 5 4 5 6]
[1 2 5 4 5 6]


# RESHAPING FUNCTION

In [18]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,0])
b=a.reshape(5,2)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9 0]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [21]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,0,9,8])
b=a.reshape(2,3,2)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9 0 9 8]
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [9 8]]]


# sum () FUNCTION

In [24]:
import numpy as np
a=np.array([1,2,3,4])
b=np.sum(a)
print(a)
print(b)

[1 2 3 4]
10


In [29]:
import numpy as np
a=np.array([[1,2,3,4],
          [5,4,6,7]])
b=np.sum(a, axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [5 4 6 7]]
[ 6  6  9 11]


# MEAN ()

In [36]:
import numpy as np
a=np.array([1,2,3,4])
b=np.mean(a)
print(a)
print(b)

[1 2 3 4]
2.5


In [52]:
 import numpy as np
a=np.array([[1,2,3,4],
          [5,6,7,8]])
b=np.mean(a,axis = 1)
print(a)
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[2.5 6.5]


# STANDERED (STD)

In [35]:
import numpy as np
a=np.array([1,2,3,4])
b=np.std(a)
print(a)
print(b)

[1 2 3 4]
1.118033988749895


In [53]:
import numpy as np
a=np.array([[1,2,3,4],
            [6,7,8,9]])
b=np.std(a,axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [6 7 8 9]]
[2.5 2.5 2.5 2.5]


# VARIANCE Array ()

In [39]:
import numpy as np
a=np.array([1,2,3,4])
b=np.var(a)
print(a)
print(b)

[1 2 3 4]
1.25


In [54]:
import numpy as np
a=np.array([[1,9,3,4],
          [9,8,7,6]])
b=np.var(a,axis = 1)
print(a)
print(b)

[[1 9 3 4]
 [9 8 7 6]]
[8.6875 1.25  ]


# MIN ()

In [42]:
import numpy as np
a=np.array([1,2,3,4])
b=np.min(a)
print(a)
print(b)

[1 2 3 4]
1


In [55]:
import numpy as np
a=np.array([[6,9,3,4],
          [4,5,6,7]])
b=np.min(a,axis = 0)
print(a)
print(b)

[[6 9 3 4]
 [4 5 6 7]]
[4 5 3 4]


# MAX ()

In [47]:
import numpy as np
a=np.array([1,2,3,4])
b=np.max(a)
print(a)
print(b)

[1 2 3 4]
4


In [57]:
import numpy as np
a=np.array([[6,9,3,4],
            [0,8,7,6]])
b=np.max(a,axis = 1)
print(a)
print(b)

[[6 9 3 4]
 [0 8 7 6]]
[9 8]
