# PANDAS SERIES

In [7]:
import numpy as np
import pandas as pd
Ser1= pd.Series([1,2,3,4])
print(Ser1)
Ser2=pd.Series(['a','b','c','d'])
print(Ser2)

0    1
1    2
2    3
3    4
dtype: int64
0    a
1    b
2    c
3    d
dtype: object


In [17]:
import numpy as np
import pandas as pd
Ser1= pd.Series([1,2,3,4], dtype="float64")
print(Ser1)
Ser2=pd.Series(['a','b','c','d'])
print(Ser2)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64
0    a
1    b
2    c
3    d
dtype: object


In [8]:
import pandas as pd
Ser1= pd.Series([1,2,3,4],index=["a","b","c","d"])
print(Ser1)

a    1
b    2
c    3
d    4
dtype: int64


In [2]:
import pandas as pd
i=pd.Index(["a","b","c","d"])
Ser1 = pd.Series([1,2,3,4],index=i)
print(Ser1)

a    1
b    2
c    3
d    4
dtype: int64


# CREATING SERIES USING DICTIONARY

In [7]:
import numpy as np
import pandas as pd
ser1=pd.Series({"Rohit":45,"kL Rahul":1,"Dk":12,"Tani":18,"Pandya":40})
print(ser1)

Rohit       45
kL Rahul     1
Dk          12
Tani        18
Pandya      40
dtype: int64


# DATAFRAMES

DATAFRAME IS COLLECTION OF MULTIPLE SERIES

In [10]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)
df = pd.DataFrame(arr ,index=['a','b','c',],columns=['A','B','C',])
print(df)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [14]:
import numpy as np
import pandas as pd
arr = np.array([[12,34,56],[500,500,500],[90,100,500]])
print(arr)
df = pd.DataFrame(arr,index = ["rahul","tani","harshad"],columns=["OSA","JAVA","PYTHON"])
print(df)

[[ 12  34  56]
 [500 500 500]
 [ 90 100 500]]
         OSA  JAVA  PYTHON
rahul     12    34      56
tani     500   500     500
harshad   90   100     500


In [15]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40,45],"JAVA":[45,56,78]})
print(df)

ValueError: All arrays must be of the same length

In [16]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40],"JAVA":[10,20,30]})
print(df)

   OSA  JAVA
0   20    10
1   30    20
2   40    30


In [19]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40],"JAVA":[20,50,80]},index = ["tanishk","harshad","rahul"])
print(df)

         OSA  JAVA
tanishk   20    20
harshad   30    50
rahul     40    80


In [21]:
import numpy as np
import pandas as pd
d = pd.Series([12,3,4,56,78,90])
c = pd.S
 eries([12,3,4,56,78])
df = pd.DataFrame({"osa":d,"java":c})
print(df)

   osa  java
0   12  12.0
1    3   3.0
2    4   4.0
3   56  56.0
4   78  78.0
5   90   NaN
