# PANDAS SERIES

In [7]:
import numpy as np
import pandas as pd
Ser1= pd.Series([1,2,3,4])
print(Ser1)
Ser2=pd.Series(['a','b','c','d'])
print(Ser2)

0    1
1    2
2    3
3    4
dtype: int64
0    a
1    b
2    c
3    d
dtype: object


In [17]:
import numpy as np
import pandas as pd
Ser1= pd.Series([1,2,3,4], dtype="float64")
print(Ser1)
Ser2=pd.Series(['a','b','c','d'])
print(Ser2)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64
0    a
1    b
2    c
3    d
dtype: object


In [8]:
import pandas as pd
Ser1= pd.Series([1,2,3,4],index=["a","b","c","d"])
print(Ser1)

a    1
b    2
c    3
d    4
dtype: int64


In [2]:
import pandas as pd
i=pd.Index(["a","b","c","d"])
Ser1 = pd.Series([1,2,3,4],index=i)
print(Ser1)

a    1
b    2
c    3
d    4
dtype: int64


# CREATING SERIES USING DICTIONARY

In [7]:
import numpy as np
import pandas as pd
ser1=pd.Series({"Rohit":45,"kL Rahul":1,"Dk":12,"Tani":18,"Pandya":40})
print(ser1)

Rohit       45
kL Rahul     1
Dk          12
Tani        18
Pandya      40
dtype: int64


# DATAFRAMES

DATAFRAME IS COLLECTION OF MULTIPLE SERIES

In [10]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)
df = pd.DataFrame(arr ,index=['a','b','c',],columns=['A','B','C',])
print(df)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [14]:
import numpy as np
import pandas as pd
arr = np.array([[12,34,56],[500,500,500],[90,100,500]])
print(arr)
df = pd.DataFrame(arr,index = ["rahul","tani","harshad"],columns=["OSA","JAVA","PYTHON"])
print(df)

[[ 12  34  56]
 [500 500 500]
 [ 90 100 500]]
         OSA  JAVA  PYTHON
rahul     12    34      56
tani     500   500     500
harshad   90   100     500


In [15]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40,45],"JAVA":[45,56,78]})
print(df)

ValueError: All arrays must be of the same length

In [16]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40],"JAVA":[10,20,30]})
print(df)

   OSA  JAVA
0   20    10
1   30    20
2   40    30


In [19]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40],"JAVA":[20,50,80]},index = ["tanishk","harshad","rahul"])
print(df)

         OSA  JAVA
tanishk   20    20
harshad   30    50
rahul     40    80


In [21]:
import numpy as np
import pandas as pd
d = pd.Series([12,3,4,56,78,90])
c = pd.S
 eries([12,3,4,56,78])
df = pd.DataFrame({"osa":d,"java":c})
print(df)

   osa  java
0   12  12.0
1    3   3.0
2    4   4.0
3   56  56.0
4   78  78.0
5   90   NaN


In [7]:
df1=pd.concat(
          [df,pd.DataFrame({
                           "Area":pd.Series(['2.1','3.1','5.5'],index=pop.index),
                          "CM":pd.Series(['bomai','shide','xyz'],index=pop.index)  
})
          ],axis=1
            )
#df1.to_csv("cities_csv")
print(df1)

            Population      Capital Area     CM
Karnataka          7.1    Bangalore  2.1  bomai
Maharashtra       12.4       Mumbai  3.1  shide
Gujarat            8.9  Gandhinagar  5.5    xyz


# CONCAT NEW COLUMN TO DATAFRAME

In [6]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="Capital")
df = pd.DataFrame({"Population":pop,"Capital":cap})
#print(df)
df1=pd.concat(
          [df,pd.DataFrame({
                           "Area":pd.Series(['2.1','3.1','5.5'],index=pop.index),
                          "CM":pd.Series(['bomai','shide','xyz'],index=pop.index)  
})
          ],axis=1
            )
#df1.to_csv("cities_csv")
df1

Population      Capital Area     CM
Karnataka          7.1    Bangalore  2.1  bomai
Maharashtra       12.4       Mumbai  3.1  shide
Gujarat            8.9  Gandhinagar  5.5    xyz

# PANDAS SUBSETTING

In [14]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [15]:
srs = Series(np.arange(5), index=["alpha","beta","gama","delta","elipson"])
srs

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32

In [16]:
srs[:2]

alpha    0
beta     1
dtype: int32

In [17]:
srs[["beta","delta"]]

beta     1
delta    3
dtype: int32

In [20]:
srs["beta":"delta"]

beta     1
gama     2
delta    3
dtype: int32

In [21]:
print(srs)
srs[srs > 3]

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32


elipson    4
dtype: int32

In [27]:
srs > 2

alpha      False
beta       False
gama       False
delta       True
elipson     True
dtype: bool

In [38]:
srs2 = Series(["zero","one","two","three","four"], index=[3,2,4,0,1])
srs2

3     zero
2      one
4      two
0    three
1     four
dtype: object

In [39]:
srs2[2:4]   

4      two
0    three
dtype: object

In [40]:
srs2[4:]   

1    four
dtype: object

In [41]:
srs2.iloc[1:4]

2      one
4      two
0    three
dtype: object

In [43]:
srs2.loc[3:4]

3    zero
2     one
4     two
dtype: object

In [44]:
srs2.loc[3:0]

3     zero
2      one
4      two
0    three
dtype: object

In [45]:
df = DataFrame(np.arange(21).reshape(7,3), columns=['AAA','BBB','CCC'], index=["alpha","beta","gama","delta","epsilon","zeta","eta"])
df

AAA  BBB  CCC
alpha      0    1    2
beta       3    4    5
gama       6    7    8
delta      9   10   11
epsilon   12   13   14
zeta      15   16   17
eta       18   19   20

In [46]:
df.AAA

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [47]:
df['AAA']

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [48]:
df[['BBB','CCC']]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [51]:
df.iloc[1:3, 1:2]

BBB
beta    4
gama    7

In [52]:
df.loc['beta':'delta', 'BBB':'CCC']

BBB  CCC
beta     4    5
gama     7    8
delta   10   11

In [53]:
df.iloc[:, 1:3]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [54]:
df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']]

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [55]:
df2 = df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']].copy()
df2

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [56]:
df2['CCC'] = Series({'alpha':11, 'gama':18, 'zeta':5})
df2

BBB  CCC
alpha    1   11
gama     7   18
zeta    16    5

In [57]:
df2.iloc[1, 1] = 2
df2

BBB  CCC
alpha    1   11
gama     7    2
zeta    16    5

In [58]:
df2.iloc[:, 1] = 0
df2

BBB  CCC
alpha    1    0
gama     7    0
zeta    16    0